title: Ralf Pfleghar
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8100358
  brandStrength: 1
  lightness: 0.8512545
  brandColors:
    - '#629AEF'
    - '#040B25'
    - '#2D5A9E'
    - '#4CAD4E'
    - '#65D85F'
  rhythmicContrast: 0.2885305
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Ralf Pfleghar
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2706093
layout_spectrum: 1
