name: Ralf Pfleghar
favicon: null
layout_spectrum: 0.5910917338915169
typography_spectrum: 0.30812193686142564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00ff00'
    - '#808000'
    - '#80ff00'
    - '#008000'
  brandStrength: 0.6875
  lightness: 0.4126842606347054
  saturation: 0.6707055228762329
  rhythmicContrast: 0.8358574924059212
purpose: []
