name: Ralf Pfleghar
favicon: null
layout_spectrum: 0.5910917338915169
typography_spectrum: 0.30812193686142564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5793364124838263
  lightness: 0.4126842606347054
  saturation: 0.6707055228762329
  rhythmicContrast: 0.8358574924059212
purpose: []
